project:
  type: website
  output-dir: _site

website:
  title: "Gary Manley Running"
  
  # FIX: Indented 2 spaces so it belongs to 'website'
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: about.qmd   
        text: "About Me"
      - href: coaching.qmd
        text: Coaching
      - text: Philosophy
        menu:
          - href: maf.qmd
            text: "The MAF Method"
          - href: happy.qmd
            text: "Be Happy"
          - href: nutrition.qmd
            text: "Nutrition"
          - href: mental.qmd
            text: "Mental Training"
          - href: strength.qmd   # New
            text: "Strength Training"
          - href: barefoot.qmd   # New
            text: "Barefoot Running"
          - href: speed.qmd      # New
            text: "Speed Work"
          - href: other.qmd      # New
            text: "Other Stuff"
      - href: library.qmd     
        text: Library
      - href: blog.qmd        # <--- ADD THIS LINE
        text: Blog

  # FIX: Indented 2 spaces so it belongs to 'website'
page-footer: 
    left: "Copyright 2025 Gary Manley Running"
    right: 
      - icon: github
        href: https://github.com/garymanley
      - icon: envelope
        href: mailto:gary@garymanleyrunning.com

format:
  html:
    theme: cosmo
    css: styles.css
    toc: false